// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3f4g8auhQq7cd41vWPI45gMBrjK-BdSg',
    appId: '1:582800287430:web:1d642eee68e3bb966619c7',
    messagingSenderId: '582800287430',
    projectId: 'demoproject1-915f4',
    authDomain: 'demoproject1-915f4.firebaseapp.com',
    storageBucket: 'demoproject1-915f4.firebasestorage.app',
    measurementId: 'G-J5C7QH08P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb4NZA5ZBMbNaKcDS9QF9oQ6_xjR9xSxc',
    appId: '1:582800287430:android:c145ec70ad3188d46619c7',
    messagingSenderId: '582800287430',
    projectId: 'demoproject1-915f4',
    storageBucket: 'demoproject1-915f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKt3eTPtWiHat7FdcLN0n4H7CX9zXf0s',
    appId: '1:582800287430:ios:ab60f1895982e9106619c7',
    messagingSenderId: '582800287430',
    projectId: 'demoproject1-915f4',
    storageBucket: 'demoproject1-915f4.firebasestorage.app',
    iosBundleId: 'com.example.baitapc11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgKt3eTPtWiHat7FdcLN0n4H7CX9zXf0s',
    appId: '1:582800287430:ios:ab60f1895982e9106619c7',
    messagingSenderId: '582800287430',
    projectId: 'demoproject1-915f4',
    storageBucket: 'demoproject1-915f4.firebasestorage.app',
    iosBundleId: 'com.example.baitapc11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3f4g8auhQq7cd41vWPI45gMBrjK-BdSg',
    appId: '1:582800287430:web:f39dadf87a518c486619c7',
    messagingSenderId: '582800287430',
    projectId: 'demoproject1-915f4',
    authDomain: 'demoproject1-915f4.firebaseapp.com',
    storageBucket: 'demoproject1-915f4.firebasestorage.app',
    measurementId: 'G-FWFYY9B6JH',
  );

}